version: "3.7"


    flask_app:
        container_name: fib-calculator
        image: "flask-fib:latest"
        restart: always
        ports:
          - "5002:5002"
        expose:
          - 5002

    nginx:
        container_name: 'nginx'
        image: "nginx:1.13.5"
        ports:
          - "80:80"
        links:
          - flask_app
        depends_on:
          - flask_app
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf

